services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "13003:8080"
        
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=Questionnaire
