create table "__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

create table re_surveys
(
    id      integer generated by default as identity
        constraint "PK_re_surveys"
            primary key,
    name    text not null,
    content text not null
);

create table re_questions
(
    id        integer generated by default as identity
        constraint "PK_re_questions"
            primary key,
    survey_id integer not null
        constraint "FK_re_questions_re_surveys_survey_id"
            references re_surveys
            on delete cascade,
    content   text    not null,
    "order"   integer default 0
);

create index "IX_re_questions_survey_id"
    on re_questions (survey_id);

create table re_answers
(
    id          integer generated by default as identity
        constraint "PK_re_answers"
            primary key,
    question_id integer not null
        constraint "FK_re_answers_re_questions_question_id"
            references re_questions
            on delete cascade,
    content     text    not null,
    "order"     integer
);

create index "IX_re_answers_question_id"
    on re_answers (question_id);

create table re_interviews
(
    id          integer generated by default as identity
        constraint "PK_re_interviews"
            primary key,
    username    text    not null,
    question_id integer not null
        constraint "FK_re_interviews_re_questions_question_id"
            references re_questions
            on delete cascade,
    answer_id   integer not null
        constraint "FK_re_interviews_re_answers_answer_id"
            references re_answers
            on delete cascade
);

create index "IX_re_interviews_answer_id"
    on re_interviews (answer_id);

create index "IX_re_interviews_question_id"
    on re_interviews (question_id);

create table re_result
(
    id             integer generated by default as identity
        constraint "PK_re_result"
            primary key,
    answer_id      integer not null
        constraint "FK_re_result_re_answers_answer_id"
            references re_answers
            on delete cascade,
    times_selected bigint  not null
);

create index "IX_re_result_answer_id"
    on re_result (answer_id);

INSERT INTO public.re_surveys (name, content) VALUES ('Опрос жителей', 'Наша команда решила провести опрос жителей для получения статистики удовлетворенности жизни в тех или иных регионах');

INSERT INTO public.re_questions (survey_id, content, "order") VALUES (1, 'В каком регоине Вы проживаете?', 1);
INSERT INTO public.re_questions (survey_id, content, "order") VALUES (1, 'Насколько вы удовлетворены жизнью в Вашем регионе?', 2);

INSERT INTO public.re_answers (question_id, content, "order") VALUES (1, 'Краснодарский край', 2);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (1, 'Ростовская область', 1);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (1, 'Красноярский край', 3);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (1, 'Московская область', 4);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (2, 'Удовлетворен', 1);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (2, 'Вполне', 2);
INSERT INTO public.re_answers (question_id, content, "order") VALUES (2, 'Не очень', 3);

INSERT INTO public.re_result (answer_id, times_selected) VALUES (1, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (4, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (5, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (6, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (7, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (2, 0);
INSERT INTO public.re_result (answer_id, times_selected) VALUES (3, 0);
